### ISSUE TITLE
Green output to spectrum

### ISSUE THREAD

**Issue by jaspervangalen** [hoppe93/SOFT2#7] opened 2020-06-05 09:20 UTC
Hi Mathias,

I'm trying to obtain the bremsstrahlung spectrum for several distribution functions and would like to use the Green output to make this process quicker. To make sure I'm doing the right thing I'm comparing the spectrum SOFT outputs with the spectrum I obtain when I manually convolve the Green output, distribution function and momentum-space Jacobian, but the results don't match.

To test this I'm outputting three arrays.
1. spectrum
2. green (`r12w`)
3. green (`r12w`, `with_f = yes`)

```plain
@DistributionFunction distfunc (numerical) {
	name = "distfunc.h5";
}

@ParticleGenerator PGen {
	a = 0.0, 1, 51;
	p = 0.1, 60.1, 61;
	xi = 0.6, 1.0, 41;
	progress = yes;
}

@RadiationOutput spectrum (spectrum) {
	output = "spectrum.h5";
	common = all;
}

@RadiationOutput green_r12w (green) {
	output = "green_r12w.h5";
	common = all;
	format = "r12w";
}

@RadiationOutput green_r12w_wf (green) {
	output = "green_r12w_wf.h5";
	common = all;
	format = "r12w";
	with_f = yes;
}
```

Then I load the outputs as follows (some details left out for clarity)

```
# Load arrays
file_spectrum = "C:/data/spectrum.h5"
file_green    = "C:/data/green_r12w.h5"
file_green_wf = "C:/data/green_r12w_wf.h5"
file_distfunc = "C:/data/distfunc.h5"

spec     = OutputSOFT(file_spectrum)
green    = OutputSOFT(file_green)
green_wf = OutputSOFT(file_green_wf)

hf = h5py.File(file_distfunc, "r")

nr_ = len(hf["r"][:])
np_ = len(hf["r0/p"][:])
nxi_ = len(hf["r0/xi"][:])

f = np.zeros((nr_, np_, nxi_))
for i in range(nr_):
    f[i, :, :] = hf["r%i" % i]["f"][:].T

hf.close()
```
When I internally multiply the Green function and distribution in SOFT and then manually apply the Jacobian I get a 1-to-1 correspondence with the SOFT spectrum output.
```
# Multiply Green function (with_f) and Jacobian
G = green_wf.func.copy()  # shape (51, 61, 41, 31)
I = np.einsum('ijkl,j->l', GF, green.param1**2) * dr * dp * dxi
print(I[:-1] / spec.I[:-1])

>>> [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
     1. 1. 1. 1. 1. 1.]
```
But, when I manually multiply the Green function with the distribution function and then momentum space Jacobian, the result does not correspond to the spectrum calculated by SOFT.

```
F = f.copy()           # shape (51, 61, 41)
G = green.func.copy()  # shape (51, 61, 41, 31)
GF = np.einsum('ijkl,ijk->ijkl', G, F)
I = np.einsum('ijkl,j->l', GF, green.param1**2) * dr * dp * dxi
print(I[:-1] / spec.I[:-1])

>>> [1.40830086 1.40843453 1.40852022 1.40859633 1.40866617 1.40873123
     1.40879381 1.40885874 1.40893586 1.40904543 1.40923222 1.4096119
     1.41044905 1.41257196 1.42014974 1.41943928 1.39460177 1.32896809
     1.24903276 1.20116468 1.13505426 1.05543201 1.0009113  0.96860324
     0.96674995 0.96428314 0.96181247 0.95918242 0.95624132 0.96044473]
```

When I enable the `with_f` flag in the green output module, what is SOFT doing different internally besides a tensor multiplication between the Green function and distribution function? Is there something besides the guiding-center and momentum-space Jacobian I'm forgetting? I did check the source code, but wasn't able to find a solution. If you could help me clarify this, I'd appreciate it.

Thanks.

**Comment by hoppe93** [comment] 2020-06-05 10:40
Hi Jasper(?),

The option "with_f" should only set a flag ("weighWithDistribution") in the "Green" module which indicates whether or not to multiply with the value of the distribution function when storing a radiation contribution. The only location where it is used is in [src/Tools/Radiation/Output/Green/Handle.cpp](https://github.com/hoppe93/SOFT2/blob/905158f4fcffadbcf391c48982e31cf5dac47a78/src/Tools/Radiation/Output/Green/Handle.cpp#L38), and so it should really be a matter of additionally multiplying the distribution, just as you say and do.

As far as I can tell your Python scripts look good, so I am not sure what is causing the discrepancy. Could you could provide at least the rest of your SOFT run script? Then I could try to reproduce your findings.

**Comment by jaspervangalen** [comment] 2020-06-05 11:24
Hi Mathias,

See the attached zip file with the input, distfunc.h5 and mf.h5.

The only thing I can imagine is SOFT uses an interpolation of distribution function, but I used the same phase-space grid for the distribution function and particle generator, so I don't think that's the issue.

Thanks,
Jasper

[input.zip](https://github.com/hoppe93/SOFT2/files/4735728/input.zip)

**Comment by hoppe93** [comment] 2020-06-07 08:53
Thanks for providing all the data and for reporting these discrepancies! I've now managed to obtain agreement between the three different approaches. It turns out that there were three different effects giving rise to the deviation, two of them being bugs. I'll give the details here for completeness.

**BUGS**
1. The most significant bug was related to lines 28-29 in [softlib/src/DistributionFunction/NumericMomentumSpaceDistributionFunction.cpp](https://github.com/hoppe93/softlib/blob/6643bbeeacecf4f64ec20427f8633fd6f569b614/src/DistributionFunction/NumericMomentumSpaceDistributionFunction.cpp#L28). Previously, the inequalities were *not* strict, leading to the distribution being set to 0 when evaluated exactly on the boundaries of the domain. Apparently, the distribution you have gives significant contributions on the domain boundary, giving most, if not all, of the deviations observed. (Most likely, this bug should not have affected previous results as we always ensure that the most dominant contributions are at the centre of the integration domain; I assume you will do so too after finishing testing)

2. A minor, although still somewhat annoying, bug was due to a faulty search algorithm in [softlib/src/DistributionFunction/NumericDistributionFunction.cpp](https://github.com/hoppe93/softlib/blob/6643bbeeacecf4f64ec20427f8633fd6f569b614/src/DistributionFunction/NumericDistributionFunction.cpp#L78). This bug would cause the momentum distribution at radial index 1 to be inserted at the very end of the distribution list, effectively being removed from the distribution. The effect of this should be minor, and indeed appears to have been so in this particular case, since the linear interpolation in radius should hide this bug.

Both of these issues are now fixed in softlib. I also found that the default interpolation algorithm used for the momentum space distributions was a bicubic spline, which is not a great idea since it can give negative values. I have hence also changed the default interpolation to bilinear in both SOFT2 and softlib.

**CAVEAT**
The third reason agreement was not perfect in your case is due to how SOFT/softlib interprets the distribution function when orbit drifts are enabled. When the drifts are enabled, the minor radius coordinate of the distribution function is interpreted as a *drift surface* label instead of a *flux surface* label (the latter being the interpretation of the coordinate ``r`` in the output Green's functions). When evaluating a distribution function, SOFT therefore accounts for the drift orbit shift and subtracts it from the radius at which to evaluate the distribution. This shifts the distribution radially (by different amounts at different radii), and generally forces softlib to interpolate radially in the distribution.

Perfect agreement is therefore difficult (but should not be impossible) to obtain when applying the distribution during vs. after the SOFT simulation. I have verified that the output is identical when drifts are disabled. I have also added a note about this caveat to the distribution function section of the documentation.

*(The reason for this difference in interpretation of the distribution is that it gives us an ad-hoc way to use distribution functions calculated with drift-less kinetic codes in SOFT with drifts enabled. Since going between the two interpretations requires interpolation in the distribution, it is not possible to use the drift-surface interpretation for distributions applied after the simulation.)*

Again, thanks for reporting this issue and for the detailed problem description!

**Closed as completed by hoppe93** 2020-06-07 08:53 UTC
Labels: bug

**Comment by jaspervangalen** [comment] 2020-06-07 17:41
Thanks Mathias for bugfixes and the helpful info regarding the usage of SOFT. I've checked my case with the new version and I'm getting the identical results now as well, at least with drifts disabled. 

Is it possible to output an array of the (average?) orbit shifts at each of the radial coordinates in e.g. the common output, so I can manually interpolate/re-evaluate the distribution function at the correct radii? If not, the difference without correcting for it seems to be about 3% (at least in the test case), which is ok for me.

Thanks again

**Comment by hoppe93** [comment] 2020-06-07 19:29
Unfortunately there's no option for outputting the drift shift as a common quantity (in principle, this should be possible, but it would require a bit of coding which I sadly don't have time for at the moment). However, it should be possible to get this separately using the ``@Orbits`` tool. The drift orbit shift is automatically stored in ``@Orbits`` output files and could be used for transforming the distribution function. Since the ``@Orbits`` output will likely be excessively large with your current simulation parameters, I would suggest using and running the following SOFT script separately:
```
<detector.pi>
tools = orb;

@ParticlePusher PPusher {
    nt = 10;
}
@Orbits orb {
    common = all;
    output = "orbits.h5";
}
```
Most of the above lines are probably NOT in the docs (sorry!) so let me explain:
- The first line includes the contents of your original SOFT script. All subsequent lines override the settings that are set in the original script.
- The drift orbit shift is calculated for the orbit as a whole, so it is only given once for every orbit. Hence, the time resolution ``nt`` can be set very low (it affects the output resolution, not the accuracy of the solution) as it will save memory.
- The ``@Orbits`` tool directly outputs the orbits calculated by SOFT. It is undocumented, but essentially the options shown above are the only available ones. The ``common`` being the same as in the ``@RadiationOutput`` modules, while ``output`` specifies the name of the output file.

It seems you've managed to get started with SOFT just fine, but in case you ever run into a SOFT-related question that you don't think fits in a GitHub issue, feel free to email me at hoppe at chalmers dot se.

**Comment by jaspervangalen** [comment] 2020-06-07 20:26
I will try that. Thanks again for the help and Ill let you know if I have any questions.
